import operator
from typing import Annotated, List
from typing_extensions import TypedDict
from pydantic import BaseModel, Field
from langchain_core.messages import BaseMessage


class StockQuery(BaseModel):
    """Extracted intent from user query."""
    symbol: str = Field(..., description="The stock ticker symbol (e.g., AAPL)")
    request_type: str = Field(..., description="Type of analysis: technical, fundamental, or general")

class FinancialMetrics(BaseModel):
    """Key financial data points."""
    current_price: float
    fifty_day_avg: float
    market_cap: int
    
class AnalysisReport(BaseModel):
    """The final output generated by the agent."""
    summary: str
    recommendation: str = Field(..., description="Buy, Sell, or Hold")
    risk_level: str

class AgentState(TypedDict):
    messages: Annotated[List[BaseMessage], operator.add]

    query_data: StockQuery | None = None
    financial_data: FinancialMetrics | None = None
    research_notes: list[str]
    final_report: AnalysisReport | None = None